"""Robotics primitives built on top of NumPy."""

from .transforms import (
    compose_transform,
    compose_transform_batch,
    euler_to_matrix,
    homogeneous_transform,
    interpolate_pose_batch,
    invert_transform,
    matrix_to_euler,
    matrix_to_quaternion,
    quaternion_to_matrix,
    rpy_to_matrix,
    rot_x,
    rot_y,
    rot_z,
    skew,
    transform_points,
    unskew,
)
from .kinematics import (
    DHLink,
    chain_positions,
    chain_positions_batch,
    dh_transform,
    forward_kinematics,
    forward_kinematics_batch,
    inverse_kinematics,
    inverse_kinematics_batch,
    robotics_backend_report,
)
from .constraints import check_joint_limits, clip_joint_values, joint_limit_violation, validate_joint_limits
from .dynamics import (
    LinkInertia,
    coriolis_forces_batch,
    forward_dynamics_batch,
    gravity_forces,
    gravity_forces_batch,
    inverse_dynamics_batch,
    mass_matrix,
    mass_matrix_batch,
)
from .jacobian import finite_difference_jacobian, geometric_jacobian, geometric_jacobian_batch, planar_2r_jacobian
from .collision import (
    BoxObstacle,
    CapsuleObstacle,
    SphereObstacle,
    chain_clearance_batch,
    chain_collision_free_batch,
    chain_collision_details_batch,
    chain_collision_summary_batch,
    chain_collision_report,
    path_collision_free,
    path_collision_summary,
    path_collision_report,
    point_obstacle_clearance,
    point_segment_distance,
    robot_collision_report,
    segment_distance,
    segment_obstacle_clearance,
)
from .trajectory import (
    cubic_time_scaling,
    joint_trajectory,
    plan_joint_path,
    plan_joint_trajectory,
    optimize_joint_path,
    smooth_joint_path,
    quintic_time_scaling,
    sample_joint_trajectory,
    sample_joint_trajectory_segments,
    trajectory_peaks_batch,
)
from .model import RobotModel
from .occupancy import VoxelOccupancyGrid
from .results import JointTrajectory, RobotResult
from .experiment import RobotExperiment, compare_robot_models
from .workcell import RobotWorkcell
from .state_estimation import PlanarPoseEKF, wrap_angle
from .urdf_model import URDFRobotModel
from .urdf_parser import URDFJoint, URDFLink, URDFSerialChain, parse_urdf, urdf_to_dh_chain
from .visualizer import plot_chain

__all__ = [
    "BoxObstacle",
    "CapsuleObstacle",
    "DHLink",
    "LinkInertia",
    "SphereObstacle",
    "chain_collision_report",
    "chain_clearance_batch",
    "chain_collision_free_batch",
    "chain_collision_details_batch",
    "chain_collision_summary_batch",
    "check_joint_limits",
    "chain_positions",
    "chain_positions_batch",
    "compose_transform",
    "compose_transform_batch",
    "coriolis_forces_batch",
    "cubic_time_scaling",
    "clip_joint_values",
    "dh_transform",
    "euler_to_matrix",
    "finite_difference_jacobian",
    "forward_kinematics",
    "forward_kinematics_batch",
    "forward_dynamics_batch",
    "geometric_jacobian",
    "geometric_jacobian_batch",
    "gravity_forces",
    "gravity_forces_batch",
    "homogeneous_transform",
    "interpolate_pose_batch",
    "invert_transform",
    "inverse_kinematics",
    "inverse_kinematics_batch",
    "inverse_dynamics_batch",
    "robotics_backend_report",
    "joint_limit_violation",
    "joint_trajectory",
    "plan_joint_path",
    "plan_joint_trajectory",
    "optimize_joint_path",
    "matrix_to_euler",
    "matrix_to_quaternion",
    "mass_matrix",
    "mass_matrix_batch",
    "path_collision_report",
    "path_collision_free",
    "path_collision_summary",
    "planar_2r_jacobian",
    "plot_chain",
    "point_obstacle_clearance",
    "point_segment_distance",
    "quaternion_to_matrix",
    "quintic_time_scaling",
    "smooth_joint_path",
    "parse_urdf",
    "RobotModel",
    "RobotResult",
    "JointTrajectory",
    "RobotExperiment",
    "RobotWorkcell",
    "robot_collision_report",
    "PlanarPoseEKF",
    "rpy_to_matrix",
    "rot_x",
    "rot_y",
    "rot_z",
    "sample_joint_trajectory",
    "sample_joint_trajectory_segments",
    "trajectory_peaks_batch",
    "segment_distance",
    "segment_obstacle_clearance",
    "URDFJoint",
    "URDFLink",
    "URDFRobotModel",
    "URDFSerialChain",
    "VoxelOccupancyGrid",
    "skew",
    "transform_points",
    "wrap_angle",
    "urdf_to_dh_chain",
    "validate_joint_limits",
    "unskew",
    "compare_robot_models",
]
