"""Compute backends and acceleration helpers."""

from .cnn_ops import col2im, im2col, maxpool_backward, maxpool_forward
from .backends import (
    active_backend,
    best_split_classifier,
    best_split_regressor,
    cpp_additive_chi2_kernel,
    cpp_chi2_kernel,
    cpp_hellinger_kernel,
    cpp_laplacian_kernel,
    cpp_rbf_kernel,
    cpp_rbf_kernel_fast,
    get_active_backend,
    pairwise_bray_curtis,
    pairwise_canberra,
    pairwise_chebyshev,
    pairwise_cosine_distances,
    pairwise_hamming_distances,
    pairwise_jaccard_distances,
    pairwise_mahalanobis_distances,
    pairwise_dist,
    pairwise_distances,
    pairwise_manhattan,
    pairwise_manhattan_distances,
    pairwise_minkowski,
    pairwise_sq_euclid,
    pairwise_squared_euclidean,
)

__all__ = [
    "active_backend",
    "best_split_classifier",
    "best_split_regressor",
    "col2im",
    "cpp_additive_chi2_kernel",
    "cpp_chi2_kernel",
    "cpp_hellinger_kernel",
    "cpp_laplacian_kernel",
    "cpp_rbf_kernel",
    "cpp_rbf_kernel_fast",
    "get_active_backend",
    "im2col",
    "maxpool_backward",
    "maxpool_forward",
    "pairwise_bray_curtis",
    "pairwise_canberra",
    "pairwise_chebyshev",
    "pairwise_cosine_distances",
    "pairwise_dist",
    "pairwise_distances",
    "pairwise_hamming_distances",
    "pairwise_jaccard_distances",
    "pairwise_mahalanobis_distances",
    "pairwise_manhattan",
    "pairwise_manhattan_distances",
    "pairwise_minkowski",
    "pairwise_sq_euclid",
    "pairwise_squared_euclidean",
]
