"""Signal processing helpers and business-oriented signal scaffolds."""

from . import augmentation as augmentation
from . import datasets as datasets
from . import detectors as detectors
from . import io as io
from . import metrics as metrics
from . import streaming as streaming
from . import transforms as transforms
from . import utils as utils

from .features import (
    hz2mel,
    hz_to_mel,
    log_mel_spec,
    log_mel_spectrogram,
    mel2hz,
    mel_bank,
    mel_filter_bank,
    mel_spec,
    mel_spectrogram,
    mel_to_hz,
    mfcc,
    rms_energy,
    spec_bw,
    spec_cent,
    spec_flat,
    spec_pow,
    spec_rolloff,
    spectral_bandwidth,
    spectral_centroid,
    spectral_flatness,
    spectral_power,
    spectral_rolloff,
    zcr,
    zero_crossing_rate,
)
from .filters import bandpass_filter, bandstop_filter, de_emph, de_emphasis, norm_sig, notch_filter, normalize_signal, pre_emph, pre_emphasis
from .core import (
    convolve1d,
    frame_signal,
    hamming_window,
    hann_window,
    istft,
    moving_average,
    overlap_add,
    stft,
)
from .detectors import CUSUMDetector, EnergyThresholdDetector, PeakDetector
from .streaming import SignalChunkBuffer, SlidingWindowStream, StreamingFeatureExtractor
from .datasets import make_chirp, make_impulse_train, make_multi_tone, make_signal_anomaly_series, make_signal_classification_dataset, make_sine_wave
from .io import load_signal, load_signal_bundle, save_signal, save_signal_bundle
from .metrics import frame_energy, signal_psnr, signal_snr
from .experiment import SignalExperiment, SignalFeatureTransformer, compare_signal_models
from .fourier import (
    FourierTransformer,
    InverseFourierTransformer,
    amplitude_spectrum,
    band_energy,
    dominant_frequency,
    fft_signal,
    fft_spectrum,
    frequency_bins,
    power_spectrum,
    inverse_fft_spectrum,
    ifft_signal,
    irfft_signal,
    phase_spectrum,
    SpectralFeatureTransformer,
    spectral_feature_vector,
    stft_spectrum,
    rfft_signal,
    top_frequency_peaks,
)
fourier_power_spectrum = power_spectrum
from .utils import chunk_signal, ensure_1d, pad_signal, resample_linear, stack_signal_features, trim_signal
from .transforms import (
    BandpassFilterTransformer,
    ISTFTTransformer,
    MFCCTransformer,
    MelSpectrogramTransformer,
    NormalizeSignalTransformer,
    PreEmphasisTransformer,
    SignalPipeline,
    SignalTransformer,
    STFTTransformer,
)

__all__ = [
    "bandpass_filter",
    "bandstop_filter",
    "augmentation",
    "BandpassFilterTransformer",
    "CUSUMDetector",
    "de_emph",
    "de_emphasis",
    "ensure_1d",
    "datasets",
    "detectors",
    "convolve1d",
    "chunk_signal",
    "frame_signal",
    "frame_energy",
    "hamming_window",
    "hann_window",
    "hz2mel",
    "hz_to_mel",
    "EnergyThresholdDetector",
    "FourierTransformer",
    "InverseFourierTransformer",
    "amplitude_spectrum",
    "SpectralFeatureTransformer",
    "mel2hz",
    "mel_bank",
    "band_energy",
    "load_signal",
    "load_signal_bundle",
    "dominant_frequency",
    "istft",
    "ISTFTTransformer",
    "io",
    "fft_signal",
    "fft_spectrum",
    "frequency_bins",
    "mel_filter_bank",
    "mel_spec",
    "mel_spectrogram",
    "log_mel_spec",
    "log_mel_spectrogram",
    "MFCCTransformer",
    "mel_to_hz",
    "mfcc",
    "MelSpectrogramTransformer",
    "fourier_power_spectrum",
    "norm_sig",
    "NormalizeSignalTransformer",
    "make_chirp",
    "make_impulse_train",
    "make_multi_tone",
    "make_signal_anomaly_series",
    "make_signal_classification_dataset",
    "make_sine_wave",
    "moving_average",
    "metrics",
    "overlap_add",
    "normalize_signal",
    "pre_emph",
    "pre_emphasis",
    "notch_filter",
    "PeakDetector",
    "PreEmphasisTransformer",
    "pad_signal",
    "phase_spectrum",
    "spectral_feature_vector",
    "resample_linear",
    "save_signal",
    "save_signal_bundle",
    "power_spectrum",
    "rms_energy",
    "spec_bw",
    "spec_cent",
    "spec_flat",
    "spec_pow",
    "spec_rolloff",
    "spectral_bandwidth",
    "spectral_centroid",
    "spectral_flatness",
    "spectral_power",
    "spectral_rolloff",
    "SignalChunkBuffer",
    "SignalExperiment",
    "SignalFeatureTransformer",
    "SignalPipeline",
    "SignalTransformer",
    "signal_psnr",
    "signal_snr",
    "rfft_signal",
    "compare_signal_models",
    "SlidingWindowStream",
    "StreamingFeatureExtractor",
    "stft_spectrum",
    "top_frequency_peaks",
    "stack_signal_features",
    "streaming",
    "STFTTransformer",
    "trim_signal",
    "zcr",
    "stft",
    "transforms",
    "utils",
    "zero_crossing_rate",
    "ifft_signal",
    "irfft_signal",
    "inverse_fft_spectrum",
]
