"""Signal-processing helpers for mathematical and numerical workflows."""

from . import advanced_spectral as advanced_spectral
from . import augmentation as augmentation
from . import correlation as correlation
from . import datasets as datasets
from . import detectors as detectors
from . import io as io
from . import metrics as metrics
from . import parametric as parametric
from . import streaming as streaming
from . import time_frequency as time_frequency
from . import transforms as transforms
from . import utils as utils
from .transforms import (
    BandpassFilterTransformer,
    ISTFTTransformer,
    MFCCTransformer,
    MelSpectrogramTransformer,
    NormalizeSignalTransformer,
    PreEmphasisTransformer,
    SignalPipeline,
    SignalTransformer,
    STFTTransformer,
)
from .utils import chunk_signal, ensure_1d, pad_signal, resample_linear, stack_signal_features, trim_signal

from .features import (
    hz2mel,
    hz_to_mel,
    log_mel_spec,
    log_mel_spectrogram,
    mel2hz,
    mel_bank,
    mel_filter_bank,
    mel_spec,
    mel_spectrogram,
    mel_to_hz,
    mfcc,
    rms_energy,
    spec_bw,
    spec_cent,
    spec_flat,
    spec_pow,
    spec_rolloff,
    spectral_bandwidth,
    spectral_centroid,
    spectral_flatness,
    spectral_power,
    spectral_rolloff,
    zcr,
    zero_crossing_rate,
)
from .filters import bandpass_filter, bandstop_filter, de_emph, de_emphasis, norm_sig, notch_filter, normalize_signal, pre_emph, pre_emphasis
from .core import (
    convolve1d,
    frame_signal,
    hamming_window,
    hann_window,
    istft,
    moving_average,
    overlap_add,
    stft,
)
from .detectors import CUSUMDetector, EnergyThresholdDetector, PeakDetector
from .streaming import SignalChunkBuffer, SlidingWindowStream, StreamingFeatureExtractor
from .datasets import make_chirp, make_impulse_train, make_multi_tone, make_signal_anomaly_series, make_signal_classification_dataset, make_sine_wave
from .io import load_signal, load_signal_bundle, save_signal, save_signal_bundle
from .metrics import frame_energy, signal_psnr, signal_snr
from .spectral import coherence, cross_power_spectrum, cross_spectrum, periodogram, welch, welch_psd
from .advanced_spectral import (
    cepstrum_peaks,
    complex_cepstrum,
    cyclic_spectral_density,
    cyclic_spectrum,
    cyclostationary_spectrum,
    envelope,
    envelope_demodulate,
    envelope_demodulation,
    envelope_spectrum,
    real_cepstrum,
)
from .correlation import (
    autocorrelation_peaks,
    correlation_peaks,
    cross_correlation_peaks,
    signal_autocorrelation,
    signal_cross_correlation,
)
from .parametric import ar_spectrum, arma_spectrum, esprit, fit_ar, fit_arma, prony
from .time_frequency import (
    analytic_signal,
    continuous_wavelet_transform,
    cwt,
    extract_ridge,
    hilbert,
    hilbert_transform,
    instantaneous_amplitude,
    instantaneous_features,
    instantaneous_frequency,
    instantaneous_phase,
    ridge,
    time_frequency_ridge,
    wavelet_power,
    wavelet_scales,
    wavelet_transform,
)
from .systems import (
    butterworth,
    butterworth_filter,
    check_stability,
    design_iir,
    filtfilt,
    freq_response,
    frequency_response,
    group_delay,
    iir_filter,
    is_stable,
    magnitude_response,
    phase_response,
    pole_zero,
    verify_filter,
    zero_phase_filter,
)
from .experiment import SignalExperiment, SignalFeatureTransformer, compare_signal_models
from .fourier import (
    FourierTransformer,
    InverseFourierTransformer,
    amplitude_spectrum,
    band_energy,
    dominant_frequency,
    fft_signal,
    fft_spectrum,
    frequency_bins,
    power_spectrum,
    inverse_fft_spectrum,
    ifft_signal,
    irfft_signal,
    phase_spectrum,
    SpectralFeatureTransformer,
    spectral_feature_vector,
    stft_spectrum,
    rfft_signal,
    top_frequency_peaks,
)
fourier_power_spectrum = power_spectrum

__all__ = [
    "bandpass_filter",
    "bandstop_filter",
    "augmentation",
    "BandpassFilterTransformer",
    "CUSUMDetector",
    "de_emph",
    "de_emphasis",
    "ensure_1d",
    "datasets",
    "detectors",
    "analytic_signal",
    "coherence",
    "continuous_wavelet_transform",
    "convolve1d",
    "cross_power_spectrum",
    "cross_spectrum",
    "cwt",
    "chunk_signal",
    "extract_ridge",
    "frame_signal",
    "freq_response",
    "frequency_response",
    "group_delay",
    "hilbert",
    "hilbert_transform",
    "instantaneous_amplitude",
    "instantaneous_features",
    "instantaneous_frequency",
    "instantaneous_phase",
    "magnitude_response",
    "phase_response",
    "pole_zero",
    "frame_energy",
    "hamming_window",
    "hann_window",
    "hz2mel",
    "hz_to_mel",
    "EnergyThresholdDetector",
    "FourierTransformer",
    "InverseFourierTransformer",
    "amplitude_spectrum",
    "SpectralFeatureTransformer",
    "mel2hz",
    "mel_bank",
    "band_energy",
    "load_signal",
    "load_signal_bundle",
    "dominant_frequency",
    "istft",
    "ISTFTTransformer",
    "io",
    "fft_signal",
    "fft_spectrum",
    "frequency_bins",
    "mel_filter_bank",
    "mel_spec",
    "mel_spectrogram",
    "log_mel_spec",
    "log_mel_spectrogram",
    "MFCCTransformer",
    "mel_to_hz",
    "mfcc",
    "MelSpectrogramTransformer",
    "fourier_power_spectrum",
    "norm_sig",
    "NormalizeSignalTransformer",
    "make_chirp",
    "make_impulse_train",
    "make_multi_tone",
    "make_signal_anomaly_series",
    "make_signal_classification_dataset",
    "make_sine_wave",
    "moving_average",
    "metrics",
    "overlap_add",
    "normalize_signal",
    "pre_emph",
    "pre_emphasis",
    "notch_filter",
    "periodogram",
    "butterworth",
    "butterworth_filter",
    "check_stability",
    "design_iir",
    "filtfilt",
    "iir_filter",
    "is_stable",
    "PeakDetector",
    "PreEmphasisTransformer",
    "pad_signal",
    "phase_spectrum",
    "spectral_feature_vector",
    "resample_linear",
    "ridge",
    "save_signal",
    "save_signal_bundle",
    "power_spectrum",
    "rms_energy",
    "spec_bw",
    "spec_cent",
    "spec_flat",
    "spec_pow",
    "spec_rolloff",
    "spectral_bandwidth",
    "spectral_centroid",
    "spectral_flatness",
    "spectral_power",
    "spectral_rolloff",
    "SignalChunkBuffer",
    "SignalExperiment",
    "SignalFeatureTransformer",
    "SignalPipeline",
    "SignalTransformer",
    "signal_psnr",
    "signal_snr",
    "rfft_signal",
    "compare_signal_models",
    "SlidingWindowStream",
    "StreamingFeatureExtractor",
    "stft_spectrum",
    "top_frequency_peaks",
    "stack_signal_features",
    "streaming",
    "time_frequency",
    "time_frequency_ridge",
    "STFTTransformer",
    "trim_signal",
    "zcr",
    "stft",
    "transforms",
    "utils",
    "zero_crossing_rate",
    "verify_filter",
    "welch",
    "welch_psd",
    "wavelet_power",
    "wavelet_scales",
    "wavelet_transform",
    "zero_phase_filter",
    "ifft_signal",
    "irfft_signal",
    "inverse_fft_spectrum",
    "advanced_spectral",
    "ar_spectrum",
    "arma_spectrum",
    "autocorrelation_peaks",
    "cepstrum_peaks",
    "complex_cepstrum",
    "correlation",
    "correlation_peaks",
    "cross_correlation_peaks",
    "cyclic_spectral_density",
    "cyclic_spectrum",
    "cyclostationary_spectrum",
    "envelope",
    "envelope_demodulate",
    "envelope_demodulation",
    "envelope_spectrum",
    "esprit",
    "fit_ar",
    "fit_arma",
    "parametric",
    "prony",
    "real_cepstrum",
    "signal_autocorrelation",
    "signal_cross_correlation",
]
